apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /stress-test
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: shared-data-claim
