apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/wanderson.leite/Downloads/apps/apache-jmeter-5.6.3/bin/testes-geekshoppingapi
